### ISSUE TITLE
Add AIS specific task to send a Safety-Related Message

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-AIS#14]
Extend ETR task with a task to instruct an AIS station to send:
- a Safety-Related Message to another AIS station
- a Safety-Related Broadcast Message

And probably more message types or subtypes depending on the simulation scenario that needs to played out.

**Comment by lofstrandbjorn** [comment]
Is this task defined in NETN-ETR or as an extension of ETR in NETN-AIS?

**Comment by bergtwvd** [comment]
These tasks are defined in NETN-AIS. The documentation has been updated already.

**Comment by bergtwvd** [comment]
Done
