### ISSUE TITLE
Align datatype naming with NETN datatype naming in general

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-AIS#31]
Proposed datatype name changes are:

Enumeration datatypes:
- MsgIdEnumType => MsgIdEnum8
- NavigationStatusEnumType => NavigationStatusEnum8
- ManeuverIndicatorEnumType => ManeuverIndicatorEnum8
- AidTypeEnumType => AidTypeEnum8
- PartNumberEnumType => PartNumberEnum8
- ShipTypeEnumType => ShipTypeEnum8

Simple datatypes:
- MMSIType => MMSIInteger32
- UnitModelType => UnitModelInteger8
- SerialNumberType => SerialNumberInteger32
- DesignatedAreaCodeType => DesignatedAreaCodeInteger32
- FunctionIdType => FunctionIdInteger32
- IMOType => IMOInteger32

Array datatypes:
- BinArrayType => BinArray
- ManufacturerIdType => ManufacturerIdArray3

@lofstrandbjorn : pls review suggested names

**Comment by lofstrandbjorn** [comment]
Looks OK. Please update accordingly.
