### ISSUE TITLE
Use NETN BASE datatypes where appropriate

### ISSUE THREAD

**Issue by lofstrandbjorn** [AMSP-04/NETN-AIS#4]
AIS module redefines some attributes now in NETN BASE. Harmonize and use NETN BASE datatypes where possible and generic datatypes should be moved to NETN BASE.

**Comment by bergtwvd** [comment]
Datatypes:

**AisNavigationData**
- RateOfTurn => NETN DegreesPerSecondFloat32 (**new**)
- SpeedOverGround => NETN SpeedMeterPerSecondFloat32
- AisPosition => NETN GeodeticLocation
- CourseOverGround => NETN DirectionDegreesFloat32
- TrueHeading => NETN DirectionDegreesFloat32
- UTCTime => NETN UTCTime (**new**)

**AisStaticAndVoyageData**
- Dimension => RPR LenghtMeterFloat32

**AisMessage9**
- Altitude => NETN AltitudeMeterFloat64 (**new**)

**Comment by bergtwvd** [comment]
Proposed changes have been implemented.

**Comment by lofstrandbjorn** [comment]
Changes to NETN-BASE
* Added SimpleDatatype DegreesPerSecondFloat32
* 
Altitude => NETN AltitudeMeterFloat64 (new)

IMO => NETN BASE IMOType (new)
Draught => NETN BASE DraughtMeterFloat32 (new)

**Comment by bergtwvd** [comment]
Added under NETN-BASE#1 Harmonize data types
