### ISSUE TITLE
Check if some attributes need to harmonize with NETN ORG

### ISSUE THREAD

**Issue by lofstrandbjorn** [AMSP-04/NETN-AIS#5]
e.g. dimensions, ship type Enum...

**Comment by bergtwvd** [comment]
- MIDcodeInt16 = NETN MIDcode (**new**)
- IMOcode => NETN IMOcode (**new**)
- ShipType => NETN ShipType (**new**)
- DimensionInt16 => RPR LenghtMeterFloat32
- TransmitterStatusEnum8 => RPR TransmitterOperationalStatusEnum8

**Comment by bergtwvd** [comment]
Proposed changes have been implemented.

**Comment by lofstrandbjorn** [comment]
Add to NETN BASE ChangeLog and CLose issue

**Comment by bergtwvd** [comment]
See https://github.com/AMSP-04/NETN-BASE/issues/1
