### ISSUE TITLE
Grammar and spelling corrections

### ISSUE THREAD

**Issue by sam-d-hall** [AMSP-04/NETN-AIS#7]
Overview.png:
- "posistion" spelling

README.md:
- replace occurrences of "to for example"

NETN-AIS.md:
- remove 'a' from "the following table shows the ASCII character to be used for a each six-bit character"
- is center or centre spelling preferred?

NETN-AIS.xml:
- replace occurrences of "to for example"
- is maneuver or manoeuvre spelling preferred?
- AisBaseStationReportAndUTCDateResponseData semantics grammar
- ManufacturerIdType semantics "manufacture’s" spelling

**Comment by lofstrandbjorn** [comment]
Overview.png:
"posistion" spelling

FIXED

**Comment by bergtwvd** [comment]
Done
